const APP_VERSION='v36.1 Payroll Upload Fix';
let currentView='overview';
let toastTimer=null;
function showToast(message){let el=document.querySelector('.toast');if(!el){el=document.createElement('div');el.className='toast';document.body.appendChild(el);}el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200);}
function renderOverview(){
  const b=budgetSnapshot(); const d=load(); const sunday=new Date().getDay()===0; const rec=Math.max(0,cents(120-b.bargeld));
  const todayPay=isSalaryDay()&&!isSalaryBookedFor(new Date());
  return `<section class="page-head"><div><p class="eyebrow">PERSÖNLICHER FINANZPLAN</p><h2>Übersicht</h2><p class="muted">Dein aktueller Budgetzyklus auf einen Blick.</p></div><div class="month-chip">${new Date().toLocaleDateString('de-DE',{month:'long',year:'numeric'})}</div></section>
  <div class="hero-grid"><button class="card balance-card tap-card" data-action="edit-giro"><div class="card-kicker">Gesamtvermögen</div><div class="hero-number">${formatEUR(b.total)}</div><div class="hero-split"><div><span>Giro</span><strong>${formatEUR(b.giro)}</strong></div><div><span>Bargeld</span><strong>${formatEUR(b.bargeld)}</strong></div></div><div class="tap-hint">Tippen zum Bearbeiten</div></button></div>
  <div class="grid-2"><div class="kpi"><span>Tagesbudget</span><strong>${formatEUR(b.dayRate)}</strong><small>${b.days} Resttage · basiert auf Giro + Bargeld</small></div><div class="kpi"><span>Wochensatz</span><strong>${formatEUR(b.weekRate)}</strong><small>7 × Tagessatz</small></div></div>
  <div class="card"><div class="section-head"><div><h3>Budgetzyklus</h3><div class="sub">Nächster Lohn: ${b.nextSalary.toLocaleDateString('de-DE')}</div></div><span class="pill">${todayPay?'Heute Lohn buchen':'1 Lohn / Monat'}</span></div><div class="budget-list"><div class="budget-line"><span>Fixkosten</span><strong>${formatEUR(b.fix)}</strong></div><div class="budget-line"><span>Giro nach Lohn* </span><strong>${formatEUR(b.giro)}</strong></div></div><div class="grid-2 actions-row"><button class="btn btn-primary" data-action="salary">€ Lohn buchen</button><button class="btn btn-secondary" data-action="open-booking">+ Buchung</button></div><div class="help">* Prognosen aus dem Gehaltsbereich verändern diesen Wert nie.</div></div>
  <div class="grid-2"><button class="card quick-card tap-card" data-action="edit-cash"><span class="quick-icon">▣</span><div><h3>Bargeld</h3><p>${formatEUR(b.bargeld)} · manuell geführt</p></div></button><button class="card quick-card tap-card" data-action="cash-correct"><span class="quick-icon">↔</span><div><h3>Wochenabschluss</h3><p>${sunday?(rec>0?`Empfehlung ${formatEUR(rec)}`:'Keine Abhebung nötig'):'Sonntag: Ziel-Bargeld 120 €'}</p></div></button></div>
  <div class="card"><div class="section-head"><div><h3>Letzter Lohn</h3><div class="sub">Bestätigte Lohnbuchung, nicht Prognose.</div></div></div>${Object.keys(d.salaryCycles).length?(()=>{const k=Object.keys(d.salaryCycles).sort().reverse()[0];const s=d.salaryCycles[k];return `<div class="budget-line"><div><strong>${escapeHtml(k)}</strong><div class="sub">Netto ${formatEUR(s.net)} · Fix ${formatEUR(s.fix)}</div></div><strong>${formatEUR(s.net-s.fix)}</strong></div>`})():'<div class="empty">Noch kein Lohnzyklus gebucht.</div>'}</div>`;
}
function renderBackup(){const d=load();return `<section class="page-head"><div><p class="eyebrow">DATENSICHERUNG</p><h2>Backup</h2><p class="muted">Lokale Daten exportieren, importieren oder zurücksetzen.</p></div><div class="month-chip">Schema v${DATA_SCHEMA_VERSION}</div></section><div class="card"><button class="btn btn-primary btn-full" data-action="export">Backup exportieren</button><button class="btn btn-secondary btn-full" data-action="import">Backup importieren</button><button class="btn btn-danger btn-full" data-action="reset">Alle Daten löschen</button></div><div class="card"><div class="notice"><strong>Gespeichert:</strong> ${d.history.length} Buchungen · ${d.fix.length} Fixkosten · ${d.payroll.entries.length} Zeitlohnarten</div></div>`;}
function renderApp(view=currentView){currentView=view;document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view));const fn={overview:renderOverview,history:renderHistory,fixed:renderFixkosten,payroll:renderPayroll,backup:renderBackup}[view]||renderOverview;document.getElementById('app').innerHTML=fn();updateConnectionPill();}
function updateConnectionPill(){const e=document.getElementById('connection-pill');if(e)e.innerHTML=`<span class="status-dot"></span>${navigator.onLine?'Online · lokal gespeichert':'Offline · lokal gespeichert'}`;}
function modal(title,body){const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.innerHTML=`<div class="modal" role="dialog" aria-modal="true"><div class="modal-head"><div><p class="eyebrow">MEIN GELDPLAN</p><h3>${title}</h3></div><button class="icon-btn" data-action="close-modal" aria-label="Schließen">×</button></div><div class="modal-body">${body}</div></div>`;document.body.appendChild(wrap);return wrap;}
function openGiroModal(){modal('Girokonto',`<div class="big-edit"><label>Aktueller Kontostand</label><div class="input-with-suffix"><input id="giro-set" class="money-input giant" inputmode="decimal" value="${load().giro.toLocaleString('de-DE',{minimumFractionDigits:2})}"><span>€</span></div><button class="btn btn-primary btn-full" data-action="save-giro">Kontostand speichern</button></div>`);}
function openCashModal(){modal('Bargeld',`<div class="big-edit"><label>Aktueller Bargeldbestand</label><div class="input-with-suffix"><input id="cash-set" class="money-input giant" inputmode="decimal" value="${load().bargeld.toLocaleString('de-DE',{minimumFractionDigits:2})}"><span>€</span></div><div class="grid-2"><button class="btn btn-primary" data-action="save-cash">Bestand setzen</button><button class="btn btn-secondary" data-action="quick-cash">± Korrektur</button></div><p class="muted">Am Lohnbuchungstag wird der Bestand ebenfalls manuell abgefragt.</p></div>`);}
function openCashCorrection(){modal('Bargeld korrigieren',`<label>Änderung in €</label><div class="input-with-suffix"><input id="cash-delta" class="money-input giant" inputmode="decimal" placeholder="+20 oder -10"><span>€</span></div><label>Beschreibung</label><input id="cash-desc" class="text-input" value="Bargeldkorrektur"><button class="btn btn-primary btn-full" data-action="apply-cash-delta">Speichern</button>`);}
function openBooking(){modal('Neue Buchung',`<div class="type-seg"><button data-type="Einnahme" class="active">Einnahme</button><button data-type="Ausgabe">Ausgabe</button><button data-type="Abheben">Abheben</button></div><label>Betrag</label><div class="input-with-suffix"><input id="booking-amount" class="money-input giant" inputmode="decimal" placeholder="0,00"><span>€</span></div><label>Beschreibung</label><input id="booking-desc" class="text-input" placeholder="z. B. Einkauf"><label>Datum</label><input id="booking-date" class="text-input" type="date" value="${new Date().toISOString().slice(0,10)}"><label>Uhrzeit</label><input id="booking-time" class="text-input" type="time" value="${new Date().toTimeString().slice(0,5)}"><button class="btn btn-primary btn-full" data-action="save-booking">Buchung speichern</button><p class="muted">Bei Abheben wird Giro vermindert und Bargeld erhöht. Bargeldausgaben werden niemals automatisch gebucht.</p>`);}
function closeModal(){document.querySelector('.modal-backdrop')?.remove();}
function saveGiro(){const v=parseMoneyInput(document.getElementById('giro-set')?.value);if(!Number.isFinite(v)||v<0){showToast('Ungültiger Kontostand');return;}const d=load();d.giro=cents(v);save(d);closeModal();renderApp(currentView);showToast('Giro gespeichert');}
function saveCash(){const v=parseMoneyInput(document.getElementById('cash-set')?.value);if(!Number.isFinite(v)||v<0){showToast('Ungültiger Bargeldbestand');return;}const d=load();d.bargeld=cents(v);save(d);closeModal();renderApp(currentView);showToast('Bargeld gespeichert');}
function applyCashDelta(){const v=parseMoneyInput(document.getElementById('cash-delta')?.value);const desc=document.getElementById('cash-desc')?.value||'Bargeldkorrektur';if(!Number.isFinite(v)||!v){showToast('Bitte eine Änderung eingeben');return;}const d=load();if(d.bargeld+v<0){showToast('Bargeld darf nicht negativ werden');return;}d.bargeld=cents(d.bargeld+v);save(d);closeModal();renderApp(currentView);showToast('Bargeld korrigiert');}
function saveBooking(){const type=document.querySelector('.type-seg button.active')?.dataset.type||'Einnahme';const amount=parseMoneyInput(document.getElementById('booking-amount')?.value);const desc=document.getElementById('booking-desc')?.value||type;const dt=`${document.getElementById('booking-date')?.value}T${document.getElementById('booking-time')?.value||'00:00'}`;if(!Number.isFinite(amount)||amount<=0){showToast('Bitte Betrag eingeben');return;}const result=addTransaction(type,amount,desc,new Date(dt));if(!result.ok){showToast(result.message);return;}closeModal();renderApp(currentView);showToast(`${type} gespeichert`);}
function exportBackup(){const payload={app:'Mein Geldplan',appVersion:APP_VERSION,schemaVersion:DATA_SCHEMA_VERSION,exportedAt:new Date().toISOString(),data:load()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`mein-geldplan-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),500);showToast('Backup exportiert');}
function importBackup(){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{const f=input.files?.[0];if(!f)return;try{const parsed=JSON.parse(await f.text());const payload=parsed?.data&&typeof parsed.data==='object'?parsed.data:parsed;const valid=validateBackupPayload(payload);if(!valid.ok){alert(valid.message);return;}if(!confirm('Backup importieren und die aktuellen Daten ersetzen?'))return;save(payload);renderApp(currentView);showToast('Backup importiert');}catch(e){alert('Backup konnte nicht gelesen werden.');}};input.click();}
function confirmReset(){if(confirm('Alle lokalen Daten wirklich löschen?'))resetAll();}

document.addEventListener('click',e=>{
  const nav=e.target.closest('.nav-item'); if(nav){renderApp(nav.dataset.view);return;}
  const act=e.target.closest('[data-action]')?.dataset.action;
  if(act==='edit-giro') openGiroModal();
  else if(act==='edit-cash') openCashModal();
  else if(act==='cash-correct') openCashCorrection();
  else if(act==='quick-cash') {closeModal();openCashCorrection();}
  else if(act==='apply-cash-delta') applyCashDelta();
  else if(act==='save-giro') saveGiro();
  else if(act==='save-cash') saveCash();
  else if(act==='salary') bookSalary();
  else if(act==='open-booking') openBooking();
  else if(act==='close-modal') closeModal();
  else if(act==='save-booking') saveBooking();
  else if(act==='undo'){const r=undoTransaction(e.target.closest('[data-id]')?.dataset.id);if(r.ok){renderApp(currentView);showToast('Buchung rückgängig gemacht');}else showToast(r.message);}
  else if(act==='export') exportBackup();
  else if(act==='import') importBackup();
  else if(act==='reset') confirmReset();
});
document.addEventListener('click',e=>{const type=e.target.closest('.type-seg button');if(type){document.querySelectorAll('.type-seg button').forEach(b=>b.classList.remove('active'));type.classList.add('active');}});
document.addEventListener('change',e=>{if(e.target.classList.contains('fix-input')) updateFixkosten(Number(e.target.dataset.index),e.target.value); if(e.target.id==='payroll-file') handlePayrollFile(e.target.files?.[0]);});
window.addEventListener('online',updateConnectionPill);window.addEventListener('offline',updateConnectionPill);
renderApp();if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{});
