import {getSavings,saveSavings} from './storage.js';
import {createSavingsPosition,addSavingsPosition,createSavingsAllocation,addSavingsAllocation,savedForPosition,savingsForSegment,maxSavingsForSegment} from './savings.js';
import {nextSegmentStart} from './cycle.js';
import {$,num,eur,dateKey} from './ui.js';

export function createSavingsUi({budgetUi,refresh=()=>{}}={}){
  function render(){const data=getSavings(),list=$('savingsList'),select=$('sSavingPosition'),b=budgetUi.getBudget(),segment=b.segmentStart?dateKey(b.segmentStart):'',already=savingsForSegment(data,segment),max=maxSavingsForSegment(b.weeklyBudget,budgetUi.getCash(),already);if($('sSaveMax'))$('sSaveMax').textContent=eur(max);if(select){const selected=select.value;select.innerHTML='<option value="">Sparposition wählen</option>';data.positions.forEach(position=>{const option=document.createElement('option');option.value=position.id;option.textContent=position.name;select.appendChild(option);});if(data.positions.some(p=>p.id===selected))select.value=selected;}if(list){list.innerHTML='';if(!data.positions.length){list.innerHTML='<div class="note">Noch keine Sparposition angelegt.</div>';return;}data.positions.forEach(position=>{const row=document.createElement('div');row.className='row';const left=document.createElement('span');left.textContent=position.name;const value=document.createElement('span');value.className='v good';value.textContent=eur(savedForPosition(data,position.id));row.append(left,value);list.appendChild(row);});}}
  function addPosition(){const name=$('sSavingName')?.value.trim()||'';if(!name)return alert('Bitte einen Namen für die Sparposition eingeben.');try{saveSavings(addSavingsPosition(getSavings(),createSavingsPosition(name)));$('sSavingName').value='';refresh();}catch(error){alert(error.message||'Sparposition konnte nicht angelegt werden.');}}
  function saveRate(){const amount=num('sSavingAmount'),positionId=$('sSavingPosition')?.value||'',b=budgetUi.getBudget();if(!b.segmentStart)return alert('Kein aktiver Budgetabschnitt gefunden.');const segment=dateKey(b.segmentStart),data=getSavings(),already=savingsForSegment(data,segment),max=maxSavingsForSegment(b.weeklyBudget,budgetUi.getCash(),already);if(amount<=0)return alert('Bitte eine positive Sparrate eingeben.');if(!positionId)return alert('Bitte eine Sparposition auswählen.');if(amount>max+0.009)return alert(`Für diesen Abschnitt kannst du maximal ${eur(max)} zusätzlich reservieren.`);const next=nextSegmentStart(b.segmentStart,b.nextPayday)||b.nextPayday;try{saveSavings(addSavingsAllocation(data,createSavingsAllocation({positionId,amount,date:dateKey(new Date()),sourceSegmentStart:segment,effectiveFrom:dateKey(next)})));$('sSavingAmount').value='';refresh();}catch(error){alert(error.message||'Sparrate konnte nicht gespeichert werden.');}}
  function init(){if($('savingPositionBtn'))$('savingPositionBtn').onclick=addPosition;if($('savingRateBtn'))$('savingRateBtn').onclick=saveRate;}
  return {init,render};
}
